#!/bin/bash

NOTE='\033[0;36m'
END_NOTE='\033[0m' # No Color


# require a space seperated list in the file
# EX: test_list file has contents:
# 'safe466.cc' 'S+PPO430.cc' 'LB0009.cc'
# strings can also be double quoted. 
# But no comma or list brackets will work
# name of the file containing list should not have an extention 
# Need full path in the list
run_from_list() {
    # echo "running tests in list " $1
    list_name="$1"
    
    if [ ! -f $list_name ]; then
        echo "List file not found."
        exit 0
    fi
    tests=$(<$list_name)
    # echo $tests

    # echo "running tests"
    for test in $tests; do
        # echo "run test" $test
        IFS=. read -r filename ext <<< "$test"
        run_single_test $filename $ext
    done
}


run_single_test() {
    if [[ "$1" != "o" ]]; then
        echo -e "${NOTE}Modifying filename: $1 --> $filename.o ${END_NOTE}"
    fi

    obj="$1.o"

    if [ ! -f $obj ]; then
        echo "Object file not found. (try make)"
        exit 0
    fi

    f="\.\.\/$obj"

    cd src
    python3 main.py -f $f ${@:2}
}



if [ $# -eq 0 ]; then
    echo "Input file not specified."
    exit 0
fi

IFS=. read -r filename ext <<< "$1"
if [[ "$ext" == "" ]]; then
    echo "will run list in " $filename "." $ext
    run_from_list $filename
    exit 0
else
    run_single_test $filename $ext
fi
