#!/bin/bash

NOTE='\033[0;36m'
END_NOTE='\033[0m' # No Color

run_single_test() {
    fileext="$3"
    if [[ "$3" != "o" ]]; then
        echo -e "${NOTE}Modifying filename: $1/$2.$3 --> $1/$2.o ${END_NOTE}"
    else
        pattern="$filename.c*"
        filename=$(find $path -maxdepth 1 -mindepth 1 -name $pattern)
        fileext="${filename##*.}"
    fi

    obj="$1/$2.o"
    
    if [ ! -f $obj ]; then
        echo "Object file not found. (try make)"
        exit 0
    fi

    f="../$obj\$$fileext"

    cd src
    python3 main.py $f ${@:4}
}



if [ $# -eq 0 ]; then
    echo "Input file not specified."
    exit 0
fi

path="${1%\/*}"
filename="${1##*\/}"
filename="${filename%.*}"
ext="${1##*.}"

if [[ "$ext" == "" ]]; then
    echo "will run list in " $filename "." $ext
    run_from_list $filename
    exit 0
else
    run_single_test $path $filename $ext ${@:2}
fi
