rmw_tests = {
    'benchmarks/cds_examples' : ['crew_3.cc', 'fib_bench_false-unreach-call.cc', 'fib_bench_false-unreach-call.cc', 'read_write_lock_unreach_13.cc', 'read_write_lock_unreach_13.cc', 'read_write_lock_unreach_12.cc', 'read_write_lock_unreach_12.cc', 'crew_2.cc', 'crew_2.cc', 'read_write_lock_3.cc', 'read_write_lock_3.cc', 'lamport_true_unreach.cc', 'lamport_true_unreach.cc', 'lamport_true_unreach.cc', 'lamport_true_unreach.cc', 'crew_1.cc', 'crew_1.cc', 'fib_bench_true-unreach-call.cc', 'fib_bench_true-unreach-call.cc', 'read_write_lock_2.cc', 'read_write_lock_2.cc', 'fib_bench_true-longest-unreach-call.cc', 'fib_bench_true-longest-unreach-call.cc', 'fib_mod_false-unreach-call.cc', 'fib_mod_false-unreach-call.cc', 'fib_mod_true-unreach-call.cc', 'fib_mod_true-unreach-call.cc', 'dekker_false-unreach-call.cc', 'dekker_false-unreach-call.cc', 'dekker_false-unreach-call.cc', 'dekker_false-unreach-call.cc', 'read_write_lock_unreach_11.cc', 'read_write_lock_unreach_11.cc', 'mot_eg_4.cc', 'mot_eg_4.cc', 'mot_eg_2.cc', 'mot_eg_2.cc', 'mot_eg_3.cc', 'mot_eg_3.cc'],
    'benchmarks/genmc_examples' : ['hwqueue-ra0.cc', 'hwqueue-ra0.cc', 'hwqueue-ra0.cc', 'hwqueue-ra0.cc', 'inc+inc+rr+w+rr0.cc', 'inc+inc+rr+w+rr0.cc'],
    'benchmarks/misc' : [],
    'benchmarks/rcmc_examples' : ['indexer0.cc'],
    'benchmarks/tracer_examples' : ['MOREDETOUR0685.cc', 'MOREDETOUR0685.cc', 'MOREDETOUR0687.cc', 'MOREDETOUR0687.cc', 'W+RWC+po+lwsync+po.cc', 'R0098.cc', 'MOREDETOUR0406.cc', 'MOREDETOUR0406.cc', 'DETOUR0895.cc', 'DETOUR0895.cc', 'WRW+2W+lwsync+po.cc', '3.2W+lwsync+lwsync+po.cc', '3.2W+lwsync+lwsync+po.cc', 'Z6.5+lwsync+rfi-data+rfi-addr.cc', 'SB0059.cc', 'DETOUR0958.cc', 'DETOUR0958.cc', 'R0119.cc', 'm5dl.cc', 'MOREDETOUR0874.cc', 'MOREDETOUR0874.cc', 'DETOUR0928.cc', 'MOREDETOUR0869.cc', 'MOREDETOUR0869.cc', 'Z6.4+po+lwsync+po.cc', 'R+po+isync.cc', 'ppc-cookbook6.1.partbarrier.cc', 'MOREDETOUR0398.cc', 'IRIW+isync+po.cc', 'Z6.0+po+addr+lwsync.cc', '2+2W0053.cc', 'Z6.4+po+po+sync.cc', 'R0102.cc', 'WRR+2W+addr+lwsync.cc'],
    'benchmarks/watts_examples' : [],
    'litmus' : [],
    'litmus/weak_fensying' : []
}